<h1>Add module</h1>

<?php
$form = $this->form;
$form->prepare();
?>

<?php echo $this->form()->openTag($form);?>
	<fieldset>
		<legend><?php echo $form->getName()?></legend>

		<?php foreach ($form as $element) {?>
			<label><?php echo $element->getLabel()?></label>
			<?php echo $this->formElement($element)?>
			<?php if($element->getOption('blockHelp')){?>
				<span class="help-block"><?php echo $element->getOption('blockHelp')?></span>
			<?php }?>
		<?php }?>

		<br /><br />
		<button type="submit" class="btn btn-primary">Submit</button>

  </fieldset>
<?php echo $this->form()->closeTag();?>