<h1>Edit module</h1>

<?php
$form = $this->form;
//$form->prepare();

?>

<?php echo $this->form()->openTag($form);?>
	<fieldset>
		<legend><?php echo $form->getName()?></legend>

		<?php foreach ($form as $element) {?>
			<?php if($element->getName()=='entity') {
                $element->setAttributes(array('disabled'=>'disabled'));
                }
                if($element->getName()=='change_protected' || $element->getName()=='icon')
                {   $element->removeAttribute('required');
                }?>
            <label><?php echo $element->getLabel()?></label>
			<?php echo $this->formElement($element)?>
			<?php if($element->getOption('blockHelp')){?>
				<span class="help-block"><?php echo $element->getOption('blockHelp')?></span>
			<?php }?>
		<?php }?>

		<br /><br />
		<button type="submit" class="btn btn-primary">Save</button>

  </fieldset>
<?php echo $this->form()->closeTag();?>