<div id="pad-wrapper" class="form-page">
	
	<a href="<?php echo $this->url('noodle/modules-manager/add')?>" class="btn btn-info btn-small" style="float: right"><i class="icon-plus"></i> Add new module</a>
	
	<h1>List of admin modules</h1>
	
	<br /><br />
	
	<?php if(count($this->flashMessages)) : ?>
	<div class="alert alert-success">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<?php foreach ($this->flashMessages as $msg) : ?>
	    	<strong>Well done!</strong> <?php echo $msg; ?><br />
	    <?php endforeach; ?>
	</div>
	<?php endif; ?>
	
	<table class="table table-bordered">
	
		<thead>
			<tr>
				<th>Module name</th>
				<th colspan="2"></th>
			</tr>
		</thead>
		<tbody>
	
			<?php foreach($this->moduleList()->getTableModules() as $module){?>
			<tr rel="<?php echo $module->id?>">
				<td><?php echo $module->module_name?></td>
				<td><a href="#" class="btn btn-warning btn-mini"><i class="icon-pencil"></i> Edit</a></td>
				<td><a href="#myModal" class="btn btn-danger btn-mini list-delete" role="button" data-toggle="modal"><i class="icon-remove"></i> Delete</a></td>
			</tr>
			<?php }?>
			<?php foreach($this->moduleList()->getVendorModules() as $module){?>
			<tr>
				<td><?php echo $module->module_name?></td>
				<td><a href="#" class="btn btn-warning btn-mini"><i class="icon-pencil"></i> Edit</a></td>
				<td><a href="#myModal" class="btn btn-danger btn-mini list-delete" role="button" data-toggle="modal"><i class="icon-remove"></i> Delete</a></td>
			</tr>
			<?php }?>
	
		</tbody>
	
	</table>
	
	<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Do you really want to delete this module?</h4>
        </div>
        <div class="modal-body">
        	<p>To continue, confirm this action.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <a href="" rel="<?php echo $this->url('noodle/modules-manager/delete', array('id' => 'ID_PLACEHOLDER'))?>" class="btn btn-danger confirm-delete">Delete this item</a>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
	
</div>