<h1>List of admin modules</h1>

<a href="<?php echo $this->url('noodle/modules-manager/add')?>" class="btn btn-info btn-small"><i class="icon-plus"></i> Add new module</a>

<br /><br />

<table class="table table-bordered">

	<thead>
		<tr>
			<th>Module name</th>
			<th colspan="2"></th>
		</tr>
	</thead>
	<tbody>

		<?php foreach($this->moduleList() as $module){?>
		<tr>
			<td><?php echo $module->module_name?></td>
			<td><a href="#" class="btn btn-warning btn-mini"><i class="icon-pencil"></i> Edit</a></td>
			<td><a href="#myModal" class="btn btn-danger btn-mini" role="button" data-toggle="modal"><i class="icon-remove"></i> Delete</a></td>
		</tr>
		<?php }?>

	</tbody>

</table>

<a href="<?php echo $this->url('noodle/modules-manager/add')?>" class="btn btn-info btn-small"><i class="icon-plus"></i> Add new module</a>

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Do you really want to delete this module?</h3>
  </div>
  <div class="modal-body">
    <p>Confirm this action (TODO)</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-danger" data-dismiss="modal">Delete this module</button>
  </div>
</div>

<br /><br />

<h1>List of repositories</h1>

<a href="<?php echo $this->url('noodle/modules-manager/add-repository')?>" class="btn btn-info btn-small"><i class="icon-plus"></i> Add new repository</a>

<br /><br />

<table class="table table-bordered">

	<thead>
		<tr>
			<th>Module name</th>
			<th colspan="2"></th>
		</tr>
	</thead>
	<tbody>

		<?php foreach($this->repositories as $key => $repository){?>
		<tr>
			<td><?php echo $repository?></td>
			<td><a href="<?php echo $this->url('modules-manager/edit-repository', array('name' => $key))?>" class="btn btn-warning btn-mini"><i class="icon-pencil"></i> Edit</a></td>
			<td><a href="#myModal" class="btn btn-danger btn-mini" role="button" data-toggle="modal"><i class="icon-remove"></i> Delete</a></td>
		</tr>
		<?php }?>

	</tbody>

</table>

<a href="<?php echo $this->url('noodle/modules-manager/add-repository')?>" class="btn btn-info btn-small"><i class="icon-plus"></i>  Add new repository</a>