<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/noodle.css')
                        ->prependStylesheet($this->basePath() . '/css/redactor/redactor.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/jquery-sortable-min.js')
                                      ->prependFile($this->basePath() . '/js/jquery-file-upload/jquery.fileupload.js')
                                      ->prependFile($this->basePath() . '/js/redactor.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery-file-upload/jquery.iframe-transport.js')
                                      ->prependFile($this->basePath() . '/js/jquery-file-upload/vendor/jquery.ui.widget.js')
                                      ->prependFile($this->basePath() . '/js/noodle.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>

    	<div class="navbar navbar-fixed-top navbar-inverse">
			<div class="navbar-inner">
				<div class="container">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
					<a class="brand" href="<?php echo $this->url('noodle') ?>">NOODLE</a>
					<div class="nav-collapse">
						<ul class="nav">
							<li class="active">
								<a href="<?php echo $this->url('noodle') ?>">Dashboard</a>
							</li>
							<!--
							<li>
								<a href="<a href="<?php echo $this->url('noodle/modules-manager') ?>">Modules manager</a>
							</li>
							-->
							<li>
								<a href="<?php echo $this->url('noodle/user/manage') ?>"><?php echo $this->translate('Users') ?></a>
							</li>
							<li>
								<a href="<?php echo $this->url('noodle/settings') ?>"><?php echo $this->translate('Settings') ?></a>
							</li>
							 
						</ul>
						<ul class="nav pull-right">
							<!--
							<li>
								<a href="#"><span class="badge badge-warning">23</span></a>
							</li>
							 -->
							<li class="divider-vertical"></li>
							<li>
								<a><?php echo date('M')?> <?php echo date('d')?>, <?php echo date('Y')?></a>
							</li>
							<li class="divider-vertical"></li>
							<li class="dropdown">
								<a data-toggle="dropdown" class="dropdown-toggle " href="#">Hello <?php echo $this->identity()->getEmail()?> <b class="caret"></b></a>
								<ul class="dropdown-menu">
								<!--
									<li>
										<a href="./account.html"><i class="icon-user"></i> Account Setting  </a>
									</li>
									<li>
										<a href="./change_password.html"><i class="icon-lock"></i> Change Password</a>
									</li>
									<li class="divider"></li>
									 -->
									<li>
										<a href="<?php echo $this->url('noodle/user/logout')?>"><i class="icon-off"></i> Logout</a>
									</li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row-fluid">
				<div class="span12">
					<div class="page-header-top">
						<div class="container">
							<?php if($this->moduleName){?>
							<div class="pull-right">
								<div class="btn-group">
									<a href="<?php echo $this->url('noodle/modules/add', array('name' => $this->moduleName))?>" class="btn btn-info"><i class="icon-plus-sign icon-white"></i> New</a>
									<button class="btn btn-info">
										<i class="icon-print icon-white"></i> Save Page As
									</button>
									<button class="btn btn-info dropdown-toggle" data-toggle="dropdown">
										<span class="caret"></span>
									</button>
									<ul class="dropdown-menu">
										<li>
											<a href="#"><i class="pull-right icon-eye-open"></i> HTML</a>
										</li>
										<li>
											<a href="#"><i class="pull-right icon-download"></i> PDF</a>
										</li>
										<li>
											<a href="#"><i class="pull-right icon-download"></i>Spreadsheet</a>
										</li>
									</ul>
								</div>
							</div>
							<?php }?>

							<?php if($this->header){?>
								<h1><?php echo $this->header?></h1>
							<?php } else {?>
								<h1>Dashboard <small>stats and info </small></h1>
							<?php }?>

						</div>
					</div>
					<div class="row-fluid">
						<div class="span3">
							<ul class="nav nav-tabs nav-stacked">
								<?php foreach($this->moduleList() as $module){?>
									<li><a href="<?php echo $this->url('noodle/modules/show', array('name' => $module->entity))?>"><?php echo $module->module_name?></a></li>
					      		<?php }?>
					      		<!--
								<li>
									<a href="./dash.html" >Dashboard <span class="label label-warning pull-right">1</span></a>
								</li>
								<li class="active">
									<a href="./table.html">Table</a>
								</li>
								 -->
							</ul>
							<!--
							<ul class="nav nav-tabs nav-stacked">

								<li>
									<a href="#">User Account</a>
								</li>
								<li>
									<a href="#">Change Password</a>
								</li>
							</ul>
						    <form class="well form-search">
							    <input type="text" class="search-query" style="width:200px" placeholder="Search whole system...">
						    </form>
						     -->
						</div>
						<div class="span9">

							<?php echo $this->content; ?>

						</div>
					</div>
				</div>
			</div>
			<hr/>
			<footer>
				 <p>&copy; 2005 - <?php echo date('Y') ?> by Massimo Filippi <?php echo $this->translate('All rights reserved.') ?></p>
			</footer>
		</div>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
