<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Noodle 2')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/noodle/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/noodle/jquery.dataTables.css')
                        ->prependStylesheet($this->basePath() . '/css/noodle/tables.css')
                        ->prependStylesheet($this->basePath() . '/css/noodle/index.css')
                        ->prependStylesheet($this->basePath() . '/css/noodle/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/css/noodle/icons.css')
                        ->prependStylesheet($this->basePath() . '/css/noodle/elements.css')
                        ->prependStylesheet($this->basePath() . '/css/noodle/layout.css')
                        ->prependStylesheet($this->basePath() . '/css/noodle/form-showcase.css')
                        ->prependStylesheet($this->basePath() . '/css/noodle/redactor.css')
                        ->prependStylesheet($this->basePath() . '/css/noodle/bootstrap-overrides.css')
                        ->prependStylesheet($this->basePath() . '/css/noodle/bootstrap.css') ?>

        <!-- open sans font -->
    	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    
    	<!-- lato font -->
    	<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
    	
        <!-- Scripts -->
        <script>
			var basePath = '<?php echo $this->basePath()?>';
        </script>
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/noodle/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/noodle/theme.js')
                                      ->prependFile($this->basePath() . '/js/noodle/jquery-sortable-min.js')
                                      ->prependFile($this->basePath() . '/js/noodle/jquery-file-upload/jquery.fileupload.js')
                                      //->prependFile($this->basePath() . '/js/noodle/dropzone.js')
                                      ->prependFile($this->basePath() . '/js/noodle/redactor.min.js')
                                      ->prependFile($this->basePath() . '/js/noodle/jquery-file-upload/jquery.iframe-transport.js')
                                      ->prependFile($this->basePath() . '/js/noodle/jquery-file-upload/vendor/jquery.ui.widget.js')
                                      ->prependFile($this->basePath() . '/js/noodle/noodle.js')
                                      ->prependFile($this->basePath() . '/js/noodle/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/noodle/jquery.min.js') ?>

        <!--[if lt IE 9]>
      		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    	<![endif]-->

    </head>
    <body>
    
    	<!-- navbar -->
	    <header class="navbar navbar-inverse" role="banner">
	        <div class="navbar-header">
	            <button class="navbar-toggle" type="button" data-toggle="collapse" id="menu-toggler">
	                <span class="sr-only">Toggle navigation</span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	            </button>
	            <a class="navbar-brand" href="<?php echo $this->url('noodle') ?>"><img src="<?php echo $this->basePath()?>/img/noodle/noodle-logo.png"></a>
	        </div>
	        <ul class="nav navbar-nav pull-right hidden-xs">
                <!--
	            <li class="hidden-xs hidden-sm">
	                <input class="search" type="text" />
	            </li>
	            -->
	            <!-- 
	            <li class="notification-dropdown hidden-xs hidden-sm">
	                <a href="#" class="trigger">
	                    <i class="icon-warning-sign"></i>
	                    <span class="count">8</span>
	                </a>
	                <div class="pop-dialog">
	                    <div class="pointer right">
	                        <div class="arrow"></div>
	                        <div class="arrow_border"></div>
	                    </div>
	                    <div class="body">
	                        <a href="#" class="close-icon"><i class="icon-remove-sign"></i></a>
	                        <div class="notifications">
	                            <h3>You have 6 new notifications</h3>
	                            <a href="#" class="item">
	                                <i class="icon-signin"></i> New user registration
	                                <span class="time"><i class="icon-time"></i> 13 min.</span>
	                            </a>
	                            <a href="#" class="item">
	                                <i class="icon-signin"></i> New user registration
	                                <span class="time"><i class="icon-time"></i> 18 min.</span>
	                            </a>
	                            <a href="#" class="item">
	                                <i class="icon-envelope-alt"></i> New message from Alejandra
	                                <span class="time"><i class="icon-time"></i> 28 min.</span>
	                            </a>
	                            <a href="#" class="item">
	                                <i class="icon-signin"></i> New user registration
	                                <span class="time"><i class="icon-time"></i> 49 min.</span>
	                            </a>
	                            <a href="#" class="item">
	                                <i class="icon-download-alt"></i> New order placed
	                                <span class="time"><i class="icon-time"></i> 1 day.</span>
	                            </a>
	                            <div class="footer">
	                                <a href="#" class="logout">View all notifications</a>
	                            </div>
	                        </div>
	                    </div>
	                </div>
	            </li>
	             -->
	            <li class="dropdown">
	                <a href="#" class="dropdown-toggle hidden-xs hidden-sm" data-toggle="dropdown">
	                    <?php echo $this->identity()->getEmail()?>
	                    <!--<b class="caret"></b>-->
	                </a>
	                <ul class="dropdown-menu">
                        <!--
	                    <li><a href="personal-info.html">Personal info</a></li>
	                    <li><a href="#">Account settings</a></li>
	                    -->
	                    <!-- 
	                    <li><a href="#">Billing</a></li>
	                    <li><a href="#">Export your data</a></li>
	                    <li><a href="#">Send feedback</a></li>
	                     -->
	                </ul>
	            </li>
                <!--
	            <li class="settings hidden-xs hidden-sm">
	                <a href="<?php echo $this->url('noodle/settings') ?>" role="button">
	                    <i class="icon-cog"></i>
	                </a>
	            </li>
	            -->
	            <li class="settings hidden-xs hidden-sm">
	                <a href="<?php echo $this->url('noodle/user/logout')?>" role="button">
	                    <i class="icon-signout"></i>
	                </a>
	            </li>
	        </ul>
	    </header>
	    <!-- end navbar -->

        <?php $roles = array(); $u_roles = $this->identity()->getRoles();foreach($u_roles as $role){$roles[] = $role->getRoleId();}?>
	    <!-- sidebar -->
	    <div id="sidebar-nav">
	        <ul id="dashboard-menu">  
	            <?php foreach($this->moduleList()->getTableModules() as $module){?>
					<li>
						<a href="<?php echo $this->url('noodle/modules/show', array('name' => $module->entity))?>">
							<i class="<?php echo $module->getIcon()?>"></i>
							<span><?php echo $module->module_name?></span>
						</a>
					</li>
	      		<?php }?>
				<?php foreach($this->moduleList()->getVendorModules() as $key => $module){?>
					<li>
						<a href="<?php echo $this->url('noodle/vendor-modules/show', array('key' => $key))?>">
							<i class="<?php echo $module->getIcon()?>"></i>
							<span><?php echo $module->getName()?></span>
						</a>
					</li>
	      		<?php }?>
                <?php if(in_array('Administrator', $roles)){?>
	            <li>
	                <a href="<?php echo $this->url('noodle/user/manage') ?>">
	                    <i class="icon-group"></i>
	                    <span>Users</span>
	                </a>
	            </li>
                <?php }?>
                <?php if(in_array('Administrator', $roles)){?>
	            <li>
	                <a href="<?php echo $this->url('noodle/modules-manager') ?>">
	                    <i class="icon-cog"></i>
	                    <span>Module settings</span>
	                </a>
	            </li>
                <?php }?>
	        </ul>
	    </div>
	    <!-- end sidebar -->
	    
	    <!-- main container -->
    	<div class="content">
    		
    		<?php echo $this->content; ?>
    		
    	</div>

    <!-- 
    	
		<div class="container">
			<div class="row-fluid">
				<div class="span12">
					<div class="page-header-top">
						<div class="container">
							<?php if($this->moduleName){?>
							<div class="pull-right">
								<div class="btn-group">
									<a href="<?php echo $this->url('noodle/modules/add', array('name' => $this->moduleName))?>" class="btn btn-info"><i class="icon-plus-sign icon-white"></i> New</a>
									<button class="btn btn-info">
										<i class="icon-print icon-white"></i> Save Page As
									</button>
									<button class="btn btn-info dropdown-toggle" data-toggle="dropdown">
										<span class="caret"></span>
									</button>
									<ul class="dropdown-menu">
										<li>
											<a href="#"><i class="pull-right icon-eye-open"></i> HTML</a>
										</li>
										<li>
											<a href="#"><i class="pull-right icon-download"></i> PDF</a>
										</li>
										<li>
											<a href="#"><i class="pull-right icon-download"></i>Spreadsheet</a>
										</li>
									</ul>
								</div>
							</div>
							<?php }?>

							<?php if($this->header){?>
								<h1><?php echo $this->header?></h1>
							<?php } else {?>
								<h1>Dashboard <small>stats and info </small></h1>
							<?php }?>

						</div>
					</div>
					<div class="row-fluid">
						<div class="span3">
							<ul class="nav nav-tabs nav-stacked">
								<?php foreach($this->moduleList()->getTableModules() as $module){?>
									<li><a href="<?php echo $this->url('noodle/modules/show', array('name' => $module->entity))?>"><?php echo $module->module_name?></a></li>
					      		<?php }?>
								<?php foreach($this->moduleList()->getVendorModules() as $module){?>
									<li>Vendor module</li>
					      		<?php }?>
							</ul>
						</div>
						<div class="span9">

							<?php //echo $this->content; ?>

						</div>
					</div>
				</div>
			</div>
			<hr/>
			<footer>
				 <p>&copy; 2005 - <?php echo date('Y') ?> by Massimo Filippi <?php echo $this->translate('All rights reserved.') ?></p>
			</footer>
		</div>
		 -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
