<div id="pad-wrapper" class="form-page">
 	
 	
                    
	<div class="row form-wrapper">
	
		<div class="col-md-12">
			<h4>Settings</h4>
			<br />
			<br />
		</div>
		
		<div class="col-md-9 column">
		
			<?php if(count($this->flashMessages)) : ?>
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<?php foreach ($this->flashMessages as $msg) : ?>
			    	<strong>Well done!</strong> <?php echo $msg; ?><br />
			    <?php endforeach; ?>
			</div>
			<?php endif; ?>
		
		    <?php
		    $form = $this->form;
		    $form->prepare();
		    ?>
	
		    <?php echo $this->form()->openTag($form);?>
				<fieldset>
	
					<?php foreach ($form as $element) {?>
						<div class="field-box">
							<label><?php echo $element->getLabel()?></label>
							<div class="col-md-8">
								<?php echo $this->formElement($element)?>
							</div>
							<?php if($element->getOption('blockHelp')){?>
								<!-- <span class="help-block"><?php echo $element->getOption('blockHelp')?></span> -->
							<?php }?>
						</div>
					<?php }?>
	
					<br /><br />
					<button type="submit" class="btn btn-primary">Save</button>
	
			  </fieldset>
			<?php echo $this->form()->closeTag();?>
			<!--
			<br /><br />
			<h4>TODO</h4>
			<ul>
				<li>Project logo</li>
				<li>Project styles</li>
				<li>Admin version / development / production</li>
				<li>Other integrations</li>
			</ul>
			-->

		</div>
		
	</div>
</div>