<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'GADOAuthSignatureMethod_HMAC_SHA1' => __DIR__ . '/src/Google_Client/OAuth.php',
    'GADOAuthConsumer' => __DIR__ . '/src/Google_Client/OAuth.php',
    'GADOAuthRequest' => __DIR__ . '/src/Google_Client/OAuth.php',
    'GADDataModel' => __DIR__ . '/src/Google_Client/gad-data-model.php',
    'GALib' => __DIR__ . '/src/Google_Client/ga-lib.php',
);