<!-- upper main stats -->
<div id="main-stats">
            <div class="row stats-row">
                <?php echo $this->GoogleAnalyticsHeader()?>
                <!-- 
                <div class="col-md-3 col-sm-3 stat">
                    <div class="data">
                        <span class="number">322</span>
                        orders
                    </div>
                    <span class="date">This week</span>
                </div>
                <div class="col-md-3 col-sm-3 stat last">
                    <div class="data">
                        <span class="number">$2,340</span>
                        sales
                    </div>
                    <span class="date">last 30 days</span>
                </div>
                 -->
            </div>
</div>
<!-- end upper main stats -->
            		        
<div id="pad-wrapper">

	Check writeable filebank_folder and _data and _cache
		
</div>

<div id="pad-wrapper">
<?php foreach($this->dashboardModules as $module){?>
	<?php echo $this->$module()?>
<?php }?>
</div>
		
		