<div id="pad-wrapper" class="form-page">
            <div class="row form-wrapper">
                <!-- left column -->
                <div class="col-md-9 column">
			                
				<?php
			    $form = $this->form;
			    //$form->setAttribute('action', $this->url('modules/add'));
			    $form->prepare();
			    ?>
			
			     <?php echo $this->form()->openTag($form);?>
					<fieldset>
						<?php foreach ($form as $element) {?>
                        <?php if(!isset($element->isHidden) || !$element->isHidden) {?>
                        <div class="field-box">
                            <label><?php echo $element->getLabel()?></label>
                            <?php if($element->getOption('blockHelp')){?>
								<span class="help-block"><?php echo $element->getOption('blockHelp')?></span>
							<?php }?>
                            <div class="col-md-8">
                                <?php echo $this->formElement($element)?>
                            </div>                            
                        </div>
                        <?php }?>
                        <?php }?>
                        
                        <br /><br />
						<button type="submit" class="btn btn-primary btn-lg">Save</button>
			
				  </fieldset>
				<?php echo $this->form()->closeTag();?>
				
				</div>
			</div>
</div>