<div id="pad-wrapper" class="form-page">
            <div class="row form-wrapper">
                <!-- left column -->
                <div class="col-md-9 column">
                    
                    <?php
				    $form = $this->form;
				    $form->prepare();
				    ?>
			
				    <?php echo $this->form()->openTag($form);?>
				    	<?php foreach ($form as $element) {?>
                        <?php if((!isset($element->isHidden) || !$element->isHidden) && !$element->getOption('hidden')) {?>
                        <div class="field-box">
                            <label><?php echo $element->getLabel()?></label>
                            <?php if($element->getOption('blockHelp')){?>
								<span class="help-block"><?php echo $element->getOption('blockHelp')?></span>
							<?php }?>
                            <div class="col-md-8">
                                <?php echo $this->formElement($element)?>
                            </div>                            
                        </div>
                        <?php }?>
                        <?php }?>
                    <?php
                    $roles = array(); $u_roles = $this->identity()->getRoles();foreach($u_roles as $role){$roles[] = $role->getRoleId();}
                    if(in_array('Administrator', $roles) || !$this->moduleName->change_protected){?>
                        <br /><br />
						<button type="submit" class="btn btn-primary btn-lg">Save</button>
						
						<a href="#myModal" class="btn" role="button" data-toggle="modal">Delete</a>
                    <?php }?>
                    <?php echo $this->form()->closeTag();?>
                </div>

                <!-- right column -->
                <div class="col-md-3 column pull-right">
                    <ul class="nav nav-pills">
						<li class="active">
							<a href="#">Main sheet</a>
						</li>
						<?php foreach($this->form->getOption('sheets') as $sheet){?>
					    	<li><a href="<?php echo $this->url('noodle/modules/edit/sheet', array('name' => $this->name, 'id' => $this->getId(), 'sheet_name' => $sheet->getName()))?>"><?php echo $sheet->getLabel()?></a></li>
					    <?php }?>
					</ul>
					
					<?php if($this->inversedModulesData){?>
						<h5>Related to:</h5>
						<?php foreach($this->inversedModulesData as $module => $data){?>
							<h6><?php echo $module?></h6>
							<ul>
							<?php foreach($data as $row){?>
								<li><a href=""><?php echo $row->getId()?></a></li>
							<?php }?>
							</ul>
						<?php }?>
					<?php }?>
                </div>
            </div>
</div>

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<form action="<?php echo $this->url('noodle/modules/delete', array('id' => $this->id, 'name' => $this->name))?>" method="post">
	  <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Do you really want to delete this item?</h3>
	  </div>
	  <div class="modal-body">
	    <?php if(isset($data) && count($data)){?>
	    <div class="alert alert-block">
			<h4>Warning!</h4>
			This item is related to another <?php echo count($data)?> items
		</div>
		<div class="well well-large">
  			<label class="radio">
				<input type="radio" name="relationHandle" id="optionsRadios1" value="setnull" checked>
				Set these to NULL
			</label>
  			<label class="radio">
				<input type="radio" name="relationHandle" id="optionsRadios1" value="delete">
				Delete all <?php echo count($data)?> related items
			</label>
			<!--
			<label class="radio">
				<input type="radio" name="relationHandle" id="optionsRadios2" value="option2">
				Change these for: TODO (load options by ajax)
			</label>
			 -->
		</div>
		<?php }?>
	  </div>
	  <div class="modal-footer">
	    	<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	    	<button class="btn btn-danger" type="submit">Delete this item</button>
	  </div>
	</form>
</div>