<div id="pad-wrapper">
            
            <?php if(count($this->flashMessages)) : ?>
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<?php foreach ($this->flashMessages as $msg) : ?>
			    	<strong>Well done!</strong> <?php echo $msg; ?><br />
			    <?php endforeach; ?>
			</div>
			<?php endif; ?>
			
            <!-- entity table-->
            <!-- the script for the toggle all checkboxes from header is located in js/theme.js -->
            <div class="table-wrapper products-table">
                <div class="row head pull-left">
                    <div class="col-md-12">
                        <h4><?php echo $this->moduleName->module_name?></h4>
                    </div>
                </div>

                <div class="filter-block">
                    <div class="pull-right">
                    	<!-- 
                        <div class="ui-select">
                            <select>
                              <option>Filter users</option>
                              <option>Signed last 30 days</option>
                              <option>Active users</option>
                            </select>
                        </div>
                        <input type="text" class="search">
                         -->
                        <?php $roles = array(); $u_roles = $this->identity()->getRoles();foreach($u_roles as $role){$roles[] = $role->getRoleId();}
                        if(in_array('Administrator', $roles) || !$this->moduleName->change_protected){?>
                            <a href="<?php echo $this->url('noodle/modules/add', array('name' => $this->name))?>" class="btn-flat success new-product">+ Add item</a>
                        <?php } else { ?>
                            <i class="icon-lock icon-2x"></i>
                        <?php } ?>
                    </div>
                </div>

                <div class="well" style="overflow: auto;">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                            	<th></th>
								<?php foreach($this->listed as $listed){?>
									<th><a href="?page=<?php echo $this->page?>&order=<?php echo (method_exists($listed, 'getOrderColumn'))?$listed->getOrderColumn():$listed->getName()?>&dir=<?php echo ($this->dir=='ASC'?'DESC':'ASC')?>"><?php echo $listed->getLabel()?></a></th>
								<?php }?>
								<th colspan="2"></th>
                            </tr>
                        </thead>
                        <tbody class="sortable">
                            <!-- row -->
                            <?php foreach($this->paginator as $row){?>
							<tr rel="<?php echo $row->getId()?>">
								<td style="width: 10px;"><input type="checkbox" value="<?php echo $row->getId()?>" name="mass_checked[]" class="mass_checked" /></td>
								<?php foreach($this->listed as $listed){?>
									<td>
										<?php if(method_exists($listed, 'getListedValue')){ echo $listed->getListedValue($row); }
											  else{ 
												if(method_exists($listed,'getValueOptions')) {
                                                    $opts = $listed->getValueOptions();
                                                    $val = $row->{$listed->getName()};
                                                    if(!isset($opts[$val]))
                                                        $var = '!N/A ('.$val.')';
                                                    else $var = $opts[$val]. ' ('.$val.')';
                                                }
                                                else
                                                {
                                                    $var = $row->{$listed->getName()};
                                                }
												if(is_object($var) && get_class($var) == 'DateTime')
												{ echo $var->format($listed->getFormat());
												}
												else 
												{ echo $var;
												}
											  }
										?>
									</td>
								<?php }?>

                                <?php if(!in_array('Administrator', $roles) && $this->moduleName->change_protected){?>
                                    <td style="width: 52px; padding-left:25px; padding-right:25px;"><a href="<?php echo $this->url('noodle/modules/edit', array('name' => $this->name, 'id' => $row->getId()))?>" class="btn btn-warning btn-sm"><i class="icon-eye-open"></i> View</a></td>
                                <?php } else { ?>
                                <td style="width: 52px; padding-left:25px; padding-right:25px;"><a href="<?php echo $this->url('noodle/modules/edit', array('name' => $this->name, 'id' => $row->getId()))?>" class="btn btn-warning btn-sm"><i class="icon-pencil"></i> Edit</a></td>
								<td style="width: 67px; padding-left:25px; padding-right:25px;"><a href="#myModal" class="btn btn-danger btn-sm list-delete" role="button" data-toggle="modal"><i class="icon-remove"></i> Delete</a></td>
                                <?php } ?>
							</tr>
							<?php }?>
                        </tbody>
                    </table>

                    <div style="display: none" id="saveOrderBtn">
                        <a href="<?php echo $this->url('noodle/modules/save-order', array('name' => $this->name))?>" class="btn btn-primary btn-sm save-order">Save New order</a>
                        <br /><br />
                    </div>
                    
                    <div class="dataTables_info" id="example_info">Showing <?php echo ($this->page-1)*10+1?> to <?php echo ($this->page-1)*10+1+$this->paginator->count()?> of <?php echo $this->paginator->getTotalItemCount()?> entries</div>
		            
		            <div class="dataTables_paginate paging_full_numbers" id="example_paginate">
		            	<a href="?page=1" tabindex="0" class="first paginate_button <?php if(1==$this->page){?>paginate_button_disabled<?php }?>" id="example_first">First</a>
		            	<!-- <a tabindex="0" class="previous paginate_button paginate_button_disabled" id="example_previous">Previous</a> -->
		            	<span>
		            		<?php for($i=1; $i<=$this->paginator->count(); $i++){?>
		            			<a href="?page=<?php echo $i?>" tabindex="0" <?php if($this->page==$i){?>class="paginate_active"<?php }?>><?php echo $i?></a>
		            		<?php }?>
		            	</span>
		            	<!-- <a tabindex="0" class="next paginate_button" id="example_next">Next</a> -->
		            	<a href="?page=<?php echo $this->paginator->count()?>" tabindex="0" class="last paginate_button <?php if($this->paginator->count()==$this->page){?>paginate_button_disabled<?php }?>" id="example_last">Last</a>
		            </div>
		            
                </div>
            </div>
            <!-- end entity table -->

</div>

<form>	
	
	<div id="massOperations" style="display: none">
		<a href="#myModal2" class="btn btn-danger btn-mini mass-delete" role="button" data-toggle="modal">Delete selected</a>
	</div>

	<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Do you really want to delete this item?</h4>
        </div>
        <div class="modal-body">
        	<p>To continue, confirm this action.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <a href="" rel="<?php echo $this->url('noodle/modules/delete', array('id' => 'ID_PLACEHOLDER', 'name' => $this->name))?>" class="btn btn-danger confirm-delete">Delete this item</a>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  
	<!-- Modal 2 -->
	<div id="myModal2" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<form action="<?php echo $this->url('noodle/modules/mass-delete', array('name' => $this->name))?>" method="post" id="massDelete">
	  <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Do you really want to delete selected items?</h3>
	  </div>
	  <div class="modal-body">
	    <p>Confirm this action</p>
	  </div>
	  <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	    <button type="submit" class="btn btn-danger confirm-delete">Delete selected items</button>
	  </div>
	</form>
	</div>
	
</form>

<script>
var currentOrderIds = new Array();
$(".sortable tr").each(function( index ) {
    var handle = $(this).find('.drag');
    if(handle){
        currentOrderIds.push(handle.data('curindex'));
    }
});
//alert(currentOrderIds);
$('.sortable').sortable({
    containerSelector: 'table',
    //itemPath: '> tbody',
    itemSelector: 'tr',
    handle: 'i.icon-move',
    //placeholder: '<tr class="placeholder"/>'
    onDrop: function($item, container, _super) {
        $(".sortable tr").each(function( index ) {
            var handle = $(this).find('.drag');
            handle.data('curindex', currentOrderIds[index]);
        });
        $('#saveOrderBtn').show();
    }
});
$('a.save-order').click(function(){
    $('#saveOrderBtn').hide();
    var args = [];
    $(".sortable tr").each(function( index ) {
        var handle = $(this).find('.drag');
        args.push({id: handle.data('objid'), order: handle.data('curindex')});
    });
    //console.log(args);
    $.post($(this).attr('href'), {
        json: args
    }, function(msg) {

    });
    return false;
});
</script>