<div id="pad-wrapper" class="form-page">
            <div class="row form-wrapper">
                <!-- left column -->
                <div class="col-md-9 column">
			                
				<?php
			    $form = $this->form;
			    //$form->setAttribute('action', $this->url('modules/add'));
			    $form->prepare();
			    ?>
			
			     <?php echo $this->form()->openTag($form);?>
					<fieldset>
			
						<div class="field-box">
                            <label><?php echo $form->get('email')->getLabel()?></label>
                            <div class="col-md-8">
                                <?php echo $this->formElement($form->get('email'))?>
                                <?php echo $this->formElementErrors($form->get('email'));?>
                            </div>                            
                        </div>
						<div class="field-box">
                            <label><?php echo $form->get('display_name')->getLabel()?></label>
                            <div class="col-md-8">
                                <?php echo $this->formElement($form->get('display_name'))?>
                                <?php echo $this->formElementErrors($form->get('display_name'));?>
                            </div>                            
                        </div>
						<div class="field-box">
                            <label><?php echo $form->get('password')->getLabel()?></label>
                            <div class="col-md-8">
                                <?php echo $this->formElement($form->get('password'))?>
                                <?php echo $this->formElementErrors($form->get('password'));?>
                            </div>                            
                        </div>
                        <div class="field-box">
                            <label><?php echo $form->get('role')->getLabel()?></label>
                            <div class="col-md-8">
                                <?php echo $this->formElement($form->get('role'))?>
                                <?php echo $this->formElementErrors($form->get('role'));?>
                            </div>
                        </div>
                        
                        <br /><br />
						<button type="submit" class="btn btn-primary btn-lg">Save</button>
			
				  </fieldset>
				<?php echo $this->form()->closeTag();?>
				
				</div>
			</div>
</div>