<div id="pad-wrapper">

	<?php if(count($this->flashMessages)) : ?>
	<div class="alert alert-success">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<?php foreach ($this->flashMessages as $msg) : ?>
	    	<strong>Well done!</strong> <?php echo $msg; ?><br />
	    <?php endforeach; ?>
	</div>
	<?php endif; ?>
	
	<div style="height: 50px">
	<div class="row head pull-left">
		<div class="col-md-12">
			<h4>Manage users</h4>
		</div>
	</div>

	<div class="filter-block">
		<div class="pull-right">
			<a href="<?php echo $this->url('noodle/user/add')?>" class="btn-flat success new-product">+ Add new user</a>
		</div>
	</div>
	</div>
	
	<table class="table table-striped table-hover">
	
		<thead>
			<tr>
				<th>User e-mail</th>
				<!--<th>Roles</th>-->
				
				<th colspan="2"></th>
			</tr>
		</thead>
		<tbody>
	
			<?php foreach($this->users as $user){?>
				<tr rel="<?php echo $user->getId()?>">
					<td><?php echo $user->getEmail()?></td>
                    <!--
					<td>
						<?php foreach($user->getRoles() as $role){?>
							<?php echo $role->getRoleId()?>
						<?php }?>
					</td>
					-->
					<td style="width: 52px; padding-left:25px; padding-right:25px;"><a href="<?php echo $this->url('noodle/user/edit', array('id' => $user->getId()))?>" class="btn btn-warning btn-sm"><i class="icon-pencil"></i> Edit</a></td>
					<td style="width: 67px; padding-left:25px; padding-right:25px;"><a href="#myModal" class="btn btn-danger btn-sm list-delete" role="button" data-toggle="modal"><i class="icon-remove"></i> Delete</a></td>
				</tr>
				<?php }?>
	
		</tbody>
	
	</table>
	
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Do you really want to delete this user?</h4>
        </div>
        <div class="modal-body">
        	<p>To continue, confirm this action.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <a href="" rel="<?php echo $this->url('noodle/user/delete', array('id' => 'ID_PLACEHOLDER'))?>" class="btn btn-danger confirm-delete">Delete this item</a>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->